FROM node:21-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

USER root
RUN npm install -g @angular/cli
RUN chmod +x /home/node/app/node_modules/.bin/ng
USER node

CMD ["ng", "serve", "--host", "0.0.0.0"]
